export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_USER_INFO = 'SET_USER_INFO';
export const DESTROY_ACCESS_TOKEN = 'DESTROY_ACCESS_TOKEN';
export const DESTROY_USER_INFO = 'DESTROY_USER_INFO';
export const FETCH_CODEGROUP_LIST = 'FETCH_CODEGROUP_LIST';
export const FETCH_CODEGROUP = 'FETCH_CODEGROUP';
export const FETCH_CODEDETAIL_LIST = 'FETCH_CODEDETAIL_LIST';
export const FETCH_CODEDETAIL = 'FETCH_CODEDETAIL';
