export const CHANGE_TODO_INPUT = 'CHANGE_TODO_INPUT';
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const REMOVE_TODO = 'REMOVE_TODO';
export const CLEAR_ALL_TODOS = 'CLEAR_ALL_TODOS';
export const RESTORE = 'RESTORE'; // 상태 복원 액션 타입
export const CHANGE_FILTER = 'CHANGE_FILTER'; // 필터링 유형 변경 액션 타입
export const EDIT_TODO = 'EDIT_TIDO'; // Todo 항목 변경 액션 타입
export const SET_EDITING_ID = 'SET_EDITING_ID'; // 편집 항목 ID 설정 액션 타입
export const RESET_EDITING_ID = 'RESET_EDITING_ID'; // 편집 항목 ID 리셋 액션 타입
