// 뮤테이션 타입 상수 선언
export const ADD_TODO = 'ADD_TODO';
export const CHECK_TODO = 'CHECK_TODO';
export const SET_EDITING_ID = 'SET_EDITING_ID';
export const RESET_EDITING_ID = 'RESET_EDITING_ID';
export const UPDATE_TODO = 'UPDATE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const CLEAR_ALL = 'CLEAR_ALL';
export const SET_FILTER = 'SET_FILTER';
export const RESTORE = 'RESTORE';
