import random

study_list = [
    '모던 자바스크립트 Deep Dive',
    '제로초 Node.js 교과서',
    '제로초 ES2021 자바스크립트',
    '자바스크립트는 모든 곳에 존재한다.',
    '자바스크립트 스킬업',
    '모던 자바스크립트 튜토리얼',
    'HTML5 웹 프로그래밍',
    'Do it! 프런트엔드 웹 디자인 입문',
    'Do it! 타입스크립트 프로그래밍',
    'Do it! 프로그레시브 웹앱 만들기',
    'Do it! 리액트 네이티브 앱 프로그래밍',
    'Java 알고리즘 문제풀이 - 인프런',
    '스프링 입문/핵심원리 - 인프런',
    '윤재성의 스프링 프레임 워크 - 인프런',
    '윤재성의 만들면서 배우는 Spring MVC 5',
    '열혈강의 자바 웹 개발 워크북',
    '명품 자바 프로그래밍',
    '프로그래밍 클로저',
    '클로저 프로그래밍의 즐거움',
    '컴퓨터 프로그래밍의 구조와 이해',
    'Learn JavaScript (online)',
    'React Tutorial (online)',
    '스칼라로 배우는 함수형 프로그래밍',
    '누구나 쉽게 스칼라+플레이 (나중에 볼 책)',
    '함수형 자바 스크립트',
    '함수형 자바 스크립트 프로그래밍 - 유인동 (나중에 볼 책)',
    'Groovy Programming - 구글 대여',
    'Learning Dart - 2nd Edition in Amazone',
    '스위프트 프로그래밍 (3판)',
    'Go언어 핵심 기초 입문 - 인프런',
    '가장 빨리 만나는 Go언어',
    'Go로 배우는 함수형 프로그래밍',
    'Go언어 웹 프로그래밍 철저 입문',
    '파이썬 중급 - 인프런',
    '윤성우의 열혈 파이썬 - 중급',
    '윤성우의 Java 프로그래밍',
    '윤성우의 C++ 프로그래밍',
    '윤성우의 열혈 자료구조',
    'Java 언어로 배우는 디자인 패턴 입문',
    '모던 자바 인 액션',
    'Masterting Swift 5',
    #'C# 프로그래밍 2판 (나중에 볼 책)',
    #'C# 교과서',
    #'ASP.NET & Core를 다르는 기술',
    '러닝 자바스크립트 ES6 (완독 도서)',
    '퍼스트캠퍼스 All-in-one_React',
    '퍼스트캠퍼스 자바 웹개발 마스터 Java_web_first_state',
    '자바 웹을 다루는 기술',
    '스프링부트 자바 웹 개발',
    'Do it! 리액트 프로그래밍 정석',
    '리액트를 다루는 기술',
    '처음 배우는 리액트 네이티브',
    '리액트 네이티브 스무디',
    '리액트 네이티브 한달 완성',
    '제로초 Vue.js 기본 강좌',
    'Do it! Vue.js 입문',
    'Vue.js 트위터 클론코딩 - 인프런',
    'Vue.js 프로젝트 투입 일주일 전',
    'Do it! 코틀린 프로그래밍',
    '깡샘의 코틀린 프로그래밍',
    #'깡샘의 안드로이드 프로그래밍',
    '자료구조와 함께 배우는 알고림즘 입문 - C언어',
    '자료구조와 함께 배우는 알고림즘 입문 - 자바',
    '자료구조와 함께 배우는 알고림즘 입문 - 파이썬',
    '파이썬 알고리즘 인터뷰',
    '파이썬 자료구조와 알고리즘',
    '다이나믹 프로그래밍 완전 정복',
    'Do it! 점프 투 장고',
    'Do it! 장고+부트스트랩 파이썬 웨 개발의 정석',
    '장고 Django로 Pinterest 만들기 - 인프런',
    #'ocaml 공식 문서',
    #'가장 쉬운 하스켈 책',
    #'퍼펙트 루비',
    '앵귤러 에센셜',
    '라라벨로 배우는 실전 PHP 프로그래밍',
    #'Laravel Up & Running',
    'Laravel로 Morden PHP 기반 Restful API 구축',
    '라라벨 배우기 (블로그 만들기)',
    'Laravel ChatApp (Jetstream)',
    'Programming in Scala 4/e',
    'Scala Cookbook',
    'Learning Scala',
    'Programming Scala 2nd',
    #'C언어의 정석',
    #'Java의 정석',
    'Svelte 인프런',
    '파이썬 동시성 프로그래밍',
    'JVM 언어 입문',
    #'머신러닝 Tensorflow.js',
    #'TLS 구현으로 배우는 암호학',
    #'JavaScript: The definitive guide',
    #'Programming Typescript',
]

random.shuffle(study_list)

select = random.choice(study_list)
print(select, '을(를) 선택하였습니다.')
