export default {
  accessToken: '',
  userInfo: null, // 사용자 정보
  codeGroups: [],
  codeGroup: null,
  codeDetails: [],
  codeDetail: null,
  jobCodes: [],
  members: [],
  member: null,
  boards: [],
  board: null,
  notices: [],
  notice: null,
  items: [],
  item: null,
  chargeCoins: [],
  payCoins: [],
  userItems: [],
  userItem: null,
};
